package com.sotska.reporter;

import com.sotska.entity.ReportData;
import dnl.utils.text.table.TextTable;

import java.io.OutputStream;
import java.io.PrintStream;

public class OutputReporter {

    public static void printReport(ReportData reportData, OutputStream outputStream) {
        var printStream = new PrintStream(outputStream);
        if (reportData.isUpdate()) {
            printStream.println("Count of updated rows: " + reportData.getUpdatedRows());
        } else {
            printStream.println("Report generated by url: " + reportData.getReportPath());
            var textTable = new TextTable((reportData).getColumnNames(), reportData.getData());
            textTable.printTable(printStream, 1);
        }
    }
}
